from matplotlib.pyplot import plot, show, legend, xlabel, ylabel, figure, title
from read_data import read_data
from jepsen_index import jepsen_index


t_ref, E_ref = read_data('ref.txt')
t_sam, E_sam = read_data('pp 0.5cnt 1.95mm.txt')
f_ref, E_ref_w, f_sam, E_sam_w, H_w, delta_phi_0_red, coefs = jepsen_index(t_ref, E_ref, t_sam, E_sam)
bins = int(f_ref.size/8)

print('Plotting data')
# figure(1)
# plot(t_ref, E_ref, label="ref")
# plot(t_sam, E_sam, label="sam")
# xlabel('Delay (ps)')
# ylabel('Pulse amplitude')
# title('Pulse vs Delay')
# legend()
# figure(2)
# plot(f_ref[:bins]*1e-12, E_ref_w[:bins], label='ref')
# plot(f_sam[:bins]*1e-12, E_sam_w[:bins], label='sam')
# xlabel('f (THz)')
# ylabel('Amplitude (dB)')
# title('Spectrum')
# legend()
# figure(3)
# plot(f_ref[:bins]*1e-12, H_w[:bins])
# xlabel('f (THz)')
# ylabel('Amplitude')
# title('Complex transfer function')
figure(4)
plot(f_ref[:bins]*1e-12, delta_phi_0_red[:bins], label='unw')
# plot(f_ref*1e-12, coefs[1] * (f_ref*1e-12) + coefs[0], label='fit')
xlabel('f (THz)')
ylabel('Phase (rad)')
title('Phase vs f')
legend()
show()
print('Closing')